---
title: "Strings and Factors"
output: github_document
date: "2023-10-17"
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
library(rvest)
library(p8105.datasets)
```

## Strings and Manuipulations 
```{r}
string_vec = c("my", "name", "is", "grace")

str_detect(string_vec, "grace")
str_detect(string_vec, "e")
str_detect(string_vec, "Grace")

str_replace(string_vec, "grace", "Grace Santos")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think") #starts with "i think"
str_detect(string_vec, "i think$") #ends with "i think"
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"Pumpkin")
str_detect(string_vec,"pumpkin")
str_detect(string_vec,"[Pp]umpkin") #either upper case or lower case
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9]")
str_detect(string_vec, "^[0-9]") #starts with number
str_detect(string_vec, "^[0-9][a-z]") #starts with number and follows with lower case letter
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") #. can be any character between 7 and 11
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") #use the \\ to indicate that [ is a special character
str_detect(string_vec, "\\[[0-9]")
```

## Factors 
```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex

as.numeric(vec_sex)

vec_sex = fct_relevel(vec_sex, "male")
vec_sex

as.numeric(vec_sex)
```

## NSDUH
```{r}

```

